name: Go Build & Deploy

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1  # Match with your Go version

      - name: Build Project
        run: go build -o public-code

      - name: Deploy to deploy branch
        run: |
          git checkout -B deploy
          git add public-code
          git commit -m "Deploy new build"
          git push --force origin deploy
