name: Go Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1  # Match with your Go version

      - name: Build Project
        run: go build -o public-code

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -T git@github.com

      - name: Checkout deploy branch
        run: |
          git fetch origin
          git checkout deploy || git checkout -b deploy

      - name: Copy build to deploy branch
        run: |
          cp public-code /tmp/public-code
          git checkout deploy
          cp /tmp/public-code .
          git add public-code
          git commit -m "Deploy new build"
          git push --force git@github.com:ether-edge/public-node.git deploy
