name: Go Build & Deploy

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

permissions:
  contents: write  # Allows pushing code to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0  # Use a stable version of Go

      - name: Build Project
        run: go build -o public-code

      - name: Stash Untracked Files
        run: |
          git add public-code
          git commit -m "Save build output before switching branches" || echo "No changes to commit"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -T git@github.com || true

      - name: Deploy to deploy branch
        run: |
          git fetch origin deploy || git branch deploy origin/deploy || git checkout -B deploy
          git checkout deploy
          git reset --hard origin/deploy || echo "No remote branch yet"
          git add public-code
          git commit -m "Deploy new build" || echo "No changes to commit"
          git push --set-upstream git@github.com:ether-edge/public-node.git deploy --force
