name: Go Build & Deploy

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

permissions:
  contents: write   # Allows writing access to repository contents (for pushing commits)
  issues: read      # Allows reading access to issues (optional, if you plan to interact with issues)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1  # Match with your Go version

      - name: Build Project
        run: go build -o public-code

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to deploy branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B deploy
          git add public-code
          git commit -m "Deploy new build"
          git push --force git@github.com:ether-edge/public-node.git deploy
