name: Go Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"  # Added quotes for version

      - name: Build Project
        run: go build -o public-code

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config --global user.name "dipto0079"
          git config --global user.email "actions@github.com"

      - name: Deploy to deploy branch
        run: |
          git remote set-url origin git@github.com:ether-edge/public-node.git
          git checkout -b deploy
          git add public-code
          git commit -m "Deploy new build [skip ci]"
          git push origin deploy --force