name: Go Build & Deploy

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

permissions:
  contents: write  # Allows pushing code to the repository
  pull-requests: write
  issues: read
  packages: none


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0  # Use a stable version of Go

      - name: Build Project
        run: go build -o public-code

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -T git@github.com || true

      - name: Stash Changes Before Switching Branch
        run: |
          git add public-code
          git commit -m "Save build output before switching branches" || echo "No changes to commit"
          git stash

      - name: Checkout Deploy Branch
        run: |
          git fetch origin deploy || true
          if git show-ref --verify --quiet refs/remotes/origin/deploy; then
            git checkout deploy
            git reset --hard origin/deploy
          else
            git checkout -B deploy
          fi

      - name: Restore Stashed Changes
        run: git stash pop || echo "Nothing to restore"

      - name: Deploy to Deploy Branch
        run: |
          git add public-code
          git commit -m "Deploy new build" || echo "No changes to commit"
          git push --force git@github.com:ether-edge/public-node.git deploy
