name: Go Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1

      - name: Build Project
        run: go build -o public-node

      - name: Deploy to deploy branch
        run: |
          git config --global user.name "ether-edge"
          git config --global user.email "info@gtfolio.com"
          git checkout -B deploy
          git add public-node
          git commit -m "Deploy new build"
          git push --force origin deploy
