name: Go Build & Deploy

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

permissions:
  contents: write  # Allows workflows to write to repository contents
  issues: read     # Allows workflows to read issue data (optional, if you need it)
  pull-requests: write  # Allows workflows to manage pull requests
  deployments: read|write|none


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1  # Match with your Go version

      - name: Build Project
        run: go build -o public-code

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -T git@github.com

      - name: Deploy to deploy branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -B deploy
          git add public-code
          git commit -m "Deploy new build"
          git push --force git@github.com:ether-edge/public-node.git deploy
